services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    image: payments-api-php
    container_name: payments-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - composer_cache:/tmp/composer
    environment:
      - COMPOSER_HOME=/tmp/composer
      - COMPOSER_CACHE_DIR=/tmp/composer/cache
    networks:
      - payments-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: payments-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - payments-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: payments-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-payments_api}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userdb}
      MYSQL_USER: ${DB_USERNAME:-userdb}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - payments-network
    ports:
      - "3306:3306"

networks:
  payments-network:
    driver: bridge

volumes:
  db-data:
  composer_cache:
